export const FETCH_ALBUMS_START = 'FETCH_ALBUMS_START'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_FAILED = 'FETCH_ALBUMS_FAILED'
export const FILTER_ALBUMS = 'FILTER_ALBUMS'

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES'

export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
export const REPLACE_FAVORITES = 'REPLACE_FAVORITES'
export const SAVE_FAVORITES_CARDS_ORDER = 'SAVE_FAVORITES_CARDS_ORDER'

export const FETCH_TODOLIST_SUCCESS = 'FETCH_TODOLIST_SUCCESS'
export const FETCH_TODOLIST_FAILED = 'FETCH_TODOLIST_FAILED'

export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
